php:
  preset: laravel
  version: 8
  disabled:
    - no_unused_imports
  finder:
    not-name:
      - index.php
      - server.php
js:
  finder:
    not-name:
      - webpack.mix.js
css: true
- name: Laravel PHPUnit
  # You may pin to the exact commit or the version.
  # uses: nathanheffley/laravel-phpunit-action@1ac680fbc5f20621343f0d7ba450a02b807c576e
  uses: nathanheffley/laravel-phpunit-action@v0.1.0
  - name: Laravel Tests
  # You may pin to the exact commit or the version.
  # uses: hdev14/laravel-test-action@7dab92e8d7ae9f2c45c86f9061a4e8d0e80bb064
  uses: hdev14/laravel-test-action@v1